server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id:  user-service
        uri: lb://user-service
        predicates:
        - Path=/user/** 
      - id:  post-service
        uri: lb://post-service
        predicates:
        - Path=/posts/**  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
 
  